# Generated by Django 5.0.7 on 2024-07-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogtagmodel_blogmodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='short_info',
            field=models.TextField(null=True),
        ),
    ]
