# Generated by Django 5.0.7 on 2024-07-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategorymodel',
            old_name='category_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='sizes',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='tags',
            new_name='tag',
        ),
    ]
