# Generated by Django 5.0.7 on 2024-07-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_category_at_productcategorymodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolormodel',
            name='code',
            field=models.CharField(max_length=7),
        ),
    ]
